# Generated by Django 5.0 on 2024-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate_management_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=100)),
                ("address", models.EmailField(max_length=100)),
                ("locaton", models.CharField(max_length=13)),
                ("features", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.AlterField(
            model_name="tenantdetails",
            name="proof",
            field=models.ImageField(upload_to="images"),
        ),
    ]
