# Generated by Django 5.0 on 2024-01-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "real_estate_management_app",
            "0002_propertydetails_alter_tenantdetails_proof",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetails",
            name="status",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
