# Generated by Django 5.0 on 2024-01-10 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "real_estate_management_app",
            "0004_alter_propertydetails_locaton_unitdetails",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("address", models.EmailField(max_length=100)),
                ("mobile", models.CharField(max_length=13)),
                ("pname", models.CharField(max_length=100)),
                ("paddress", models.EmailField(max_length=100)),
                ("locaton", models.CharField(max_length=130)),
                ("features", models.CharField(max_length=500)),
                ("uname", models.EmailField(max_length=100)),
                ("rent_cost", models.CharField(max_length=13)),
                ("types", models.CharField(max_length=500)),
                ("enddate", models.CharField(max_length=500)),
                ("rentdate", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=10)),
                (
                    "properti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate_management_app.propertydetails",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate_management_app.unitdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
