# Generated by Django 5.0 on 2024-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate_management_app", "0005_rentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="pname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
